version: '3'
services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    volumes:
      - .:/census
    depends_on:
      - postgres
